Repository kambok/kambokweb, pull requests merged in 2022-09, with the labels that each got.

#5 Final push!
  nbproject/project.properties
  src/java/Admin/Adduser.java
  src/java/Investor/InvestorInterestReturn.java
  src/java/data/Database.java
  src/java/model/Ads.java
  src/java/model/MyListener.java
  web/Adminhome.jsp
  web/Advertisement.jsp
  web/WEB-INF/web.xml
  web/investment-news-feed.jsp
  web/investordashboard.jsp
Labels: good first issue

#6 Create LICENSE.md
  LICENSE.md
Labels: documentation

#9 Staffmanagement
  src/java/Admin/Adduser.java
  src/java/Admin/DeleteStaff.java
  src/java/Admin/edit.java
  src/java/Admin/saveEditStaff.java
  src/java/Admin/viewStaff.java
  src/java/Investor/SetAuthorizationPin.java
  src/java/data/Database.java
  src/java/model/InvestorDetails.java
  src/java/model/MyListener.java
  web/Adminhome.jsp
  web/WEB-INF/web.xml
  web/create-account.webp
  web/deleteStaff.jsp
  web/editStaff.jsp
  web/errorpage.jsp
  web/index.jsp
  web/investor-bio.jsp
  web/investor-tpin.jsp
  web/loanrequest.jsp
  web/register.jsp
  web/signup.jpg
  web/staffmanagement.jsp
  web/viewStaff.jsp
Labels: enhancement

#10 Investor extra
  src/java/Investor/InvestorInterestReturn.java
  src/java/data/Database.java
  web/Invest.jsp
  web/investordashboard.jsp
Labels: enhancement

#11 Investordashboard
  src/java/Investor/LoanInvest.java
  web/Invest.jsp
  web/investment-news-feed.jsp
  web/investordashboard.jsp
Labels: enhancement
